export const ships = [
    {
        id: 0,
        manufacturer: 'RSI',
        model: 'Polaris',
        missileSize: 3,
        torpedoSize: 10,
        missileLaunchers: [
            {
                id: 1,
                name: 'Forward Launcher',
                selectedMissile: {
                    type: 'Missile',
                    subType: 'Missile',
                    size: 3,
                    grade: 'A',
                    name: 'Arrester III',
                    shortName: 'Arrstr III',
                    description:
                        'Using cross section targeting to hunt for its prey, the Firestorm Arrester proximity missile makes quick work of enemies caught in the crosshairs.',
                    physics: {
                        mass: 119,
                        temperature: {
                            enable: false,
                            initialTemperature: -1,
                            coolingEqualizationMultiplier: true,
                            internalTemperatureGeneration: false,
                            signatureParams: {
                                enable: false,
                                minimumTemperatureForIR: 250,
                                temperatureToIR: 6,
                            },
                            itemResourceParams: {
                                minOperatingTemperature: 0,
                                minCoolingTemperature: 300,
                                enableOverheat: false,
                                overheatTemperature: 450,
                                overheatWarningTemperature: 370,
                                overheatRecoveryTemperature: 350,
                            },
                        },
                    },
                    health: {
                        hp: 50,
                        damageResistanceMultiplier: {
                            physical: 1,
                            energy: 1,
                            distortion: 1,
                            thermal: 1,
                            biochemical: 0,
                            stun: 0,
                        },
                    },
                    ref: 'dee6efca-71ef-438c-b762-624f9ce649f3',
                    distortion: {
                        decayDelay: 1.5,
                        decayRate: 40,
                        maximum: 1000,
                        warningRatio: 0.75,
                        recoveryRatio: 0.7,
                        powerRatioAtMaxDistortion: false,
                        powerChangeOnlyAtMaxDistortion: true,
                    },
                    missile: {
                        explosionSafetyDistance: 5,
                        projectileProximity: 1,
                        armTime: 1.5,
                        igniteTime: 0.3,
                        collisionDelayTime: 0.5,
                        irSignalMinValue: 0,
                        irSignalMaxValue: 0,
                        irSignalRiseRate: 0,
                        irSignalDecayRate: 0,
                        trackingSignalType: 'CrossSection',
                        lockSignalAmplifier: 2.5,
                        lockTime: 1,
                        lockingAngle: 60,
                        minRatioForLock: 1,
                        lockIncreaseRate: 1.3,
                        lockDecreaseRate: 9999,
                        lockRangeMin: 1900,
                        lockRangeMax: 25000,
                        lockResolutionRadius: 700,
                        signalResilienceMin: 1,
                        signalResilienceMax: 1.7,
                        linearSpeed: 857.5,
                        fuelTankSize: 50,
                        maxLifetime: 0,
                        minRadius: 0.25,
                        maxRadius: 3,
                        minPhysRadius: 20,
                        maxPhysRadius: 25,
                        hitType: 'explosion',
                        damage: {
                            damagePhysical: 2526.42,
                            damageEnergy: 0,
                            damageDistortion: 0,
                            damageThermal: 0,
                            damageBiochemical: 0,
                            damageStun: 0,
                        },
                    },
                    manufacturerData: {
                        calculatorType: 'manufacturer',
                        data: {
                            nameSmall: 'FSKI',
                            ref: '5f81335d-44e6-4104-841e-c5af9df06829',
                            name: 'FireStorm Kinetics',
                            calculatorName: 'FSKI',
                        },
                    },
                },
                missileArmedCount: 1,
            },
            {
                id: 2,
                name: 'Missile Turret',
                selectedMissile: {
                    type: 'Missile',
                    subType: 'Missile',
                    size: 3,
                    grade: 'A',
                    name: 'Arrester III',
                    shortName: 'Arrstr III',
                    description:
                        'Using cross section targeting to hunt for its prey, the Firestorm Arrester proximity missile makes quick work of enemies caught in the crosshairs.',
                    physics: {
                        mass: 119,
                        temperature: {
                            enable: false,
                            initialTemperature: -1,
                            coolingEqualizationMultiplier: true,
                            internalTemperatureGeneration: false,
                            signatureParams: {
                                enable: false,
                                minimumTemperatureForIR: 250,
                                temperatureToIR: 6,
                            },
                            itemResourceParams: {
                                minOperatingTemperature: 0,
                                minCoolingTemperature: 300,
                                enableOverheat: false,
                                overheatTemperature: 450,
                                overheatWarningTemperature: 370,
                                overheatRecoveryTemperature: 350,
                            },
                        },
                    },
                    health: {
                        hp: 50,
                        damageResistanceMultiplier: {
                            physical: 1,
                            energy: 1,
                            distortion: 1,
                            thermal: 1,
                            biochemical: 0,
                            stun: 0,
                        },
                    },
                    ref: 'dee6efca-71ef-438c-b762-624f9ce649f3',
                    distortion: {
                        decayDelay: 1.5,
                        decayRate: 40,
                        maximum: 1000,
                        warningRatio: 0.75,
                        recoveryRatio: 0.7,
                        powerRatioAtMaxDistortion: false,
                        powerChangeOnlyAtMaxDistortion: true,
                    },
                    missile: {
                        explosionSafetyDistance: 5,
                        projectileProximity: 1,
                        armTime: 1.5,
                        igniteTime: 0.3,
                        collisionDelayTime: 0.5,
                        irSignalMinValue: 0,
                        irSignalMaxValue: 0,
                        irSignalRiseRate: 0,
                        irSignalDecayRate: 0,
                        trackingSignalType: 'CrossSection',
                        lockSignalAmplifier: 2.5,
                        lockTime: 1,
                        lockingAngle: 60,
                        minRatioForLock: 1,
                        lockIncreaseRate: 1.3,
                        lockDecreaseRate: 9999,
                        lockRangeMin: 1900,
                        lockRangeMax: 25000,
                        lockResolutionRadius: 700,
                        signalResilienceMin: 1,
                        signalResilienceMax: 1.7,
                        linearSpeed: 857.5,
                        fuelTankSize: 50,
                        maxLifetime: 0,
                        minRadius: 0.25,
                        maxRadius: 3,
                        minPhysRadius: 20,
                        maxPhysRadius: 25,
                        hitType: 'explosion',
                        damage: {
                            damagePhysical: 2526.42,
                            damageEnergy: 0,
                            damageDistortion: 0,
                            damageThermal: 0,
                            damageBiochemical: 0,
                            damageStun: 0,
                        },
                    },
                    manufacturerData: {
                        calculatorType: 'manufacturer',
                        data: {
                            nameSmall: 'FSKI',
                            ref: '5f81335d-44e6-4104-841e-c5af9df06829',
                            name: 'FireStorm Kinetics',
                            calculatorName: 'FSKI',
                        },
                    },
                },
                missileArmedCount: 1,
            },
        ],
        pdcCount: 7,
    },
    {
        id: 1,
        manufacturer: 'Origin Jumpworks',
        model: '890 Jump',
        missileSize: 3,
        torpedoSize: null,
        pdcCount: 7,
    },
]

export const shipOptions = [
    {
        label: '890 Jump',
        value: {
            id: 1,
            manufacturer: 'Origin Jumpworks',
            model: '890 Jump',
            missileSize: 3,
            torpedoSize: null,
            pdcCount: 7,
        },
    },
    {
        label: 'Polaris',
        value: {
            id: 0,
            manufacturer: 'RSI',
            model: 'Polaris',
            missileSize: 3,
            torpedoSize: 10,
            missileLaunchers: [
                {
                    id: 1,
                    name: 'Forward Launcher',
                    selectedMissile: {
                        type: 'Missile',
                        subType: 'Missile',
                        size: 3,
                        grade: 'A',
                        name: 'Arrester III',
                        shortName: 'Arrstr III',
                        description:
                            'Using cross section targeting to hunt for its prey, the Firestorm Arrester proximity missile makes quick work of enemies caught in the crosshairs.',
                        physics: {
                            mass: 119,
                            temperature: {
                                enable: false,
                                initialTemperature: -1,
                                coolingEqualizationMultiplier: true,
                                internalTemperatureGeneration: false,
                                signatureParams: {
                                    enable: false,
                                    minimumTemperatureForIR: 250,
                                    temperatureToIR: 6,
                                },
                                itemResourceParams: {
                                    minOperatingTemperature: 0,
                                    minCoolingTemperature: 300,
                                    enableOverheat: false,
                                    overheatTemperature: 450,
                                    overheatWarningTemperature: 370,
                                    overheatRecoveryTemperature: 350,
                                },
                            },
                        },
                        health: {
                            hp: 50,
                            damageResistanceMultiplier: {
                                physical: 1,
                                energy: 1,
                                distortion: 1,
                                thermal: 1,
                                biochemical: 0,
                                stun: 0,
                            },
                        },
                        ref: 'dee6efca-71ef-438c-b762-624f9ce649f3',
                        distortion: {
                            decayDelay: 1.5,
                            decayRate: 40,
                            maximum: 1000,
                            warningRatio: 0.75,
                            recoveryRatio: 0.7,
                            powerRatioAtMaxDistortion: false,
                            powerChangeOnlyAtMaxDistortion: true,
                        },
                        missile: {
                            explosionSafetyDistance: 5,
                            projectileProximity: 1,
                            armTime: 1.5,
                            igniteTime: 0.3,
                            collisionDelayTime: 0.5,
                            irSignalMinValue: 0,
                            irSignalMaxValue: 0,
                            irSignalRiseRate: 0,
                            irSignalDecayRate: 0,
                            trackingSignalType: 'CrossSection',
                            lockSignalAmplifier: 2.5,
                            lockTime: 1,
                            lockingAngle: 60,
                            minRatioForLock: 1,
                            lockIncreaseRate: 1.3,
                            lockDecreaseRate: 9999,
                            lockRangeMin: 1900,
                            lockRangeMax: 25000,
                            lockResolutionRadius: 700,
                            signalResilienceMin: 1,
                            signalResilienceMax: 1.7,
                            linearSpeed: 857.5,
                            fuelTankSize: 50,
                            maxLifetime: 0,
                            minRadius: 0.25,
                            maxRadius: 3,
                            minPhysRadius: 20,
                            maxPhysRadius: 25,
                            hitType: 'explosion',
                            damage: {
                                damagePhysical: 2526.42,
                                damageEnergy: 0,
                                damageDistortion: 0,
                                damageThermal: 0,
                                damageBiochemical: 0,
                                damageStun: 0,
                            },
                        },
                        manufacturerData: {
                            calculatorType: 'manufacturer',
                            data: {
                                nameSmall: 'FSKI',
                                ref: '5f81335d-44e6-4104-841e-c5af9df06829',
                                name: 'FireStorm Kinetics',
                                calculatorName: 'FSKI',
                            },
                        },
                    },
                },
                {
                    id: 2,
                    name: 'Missile Turret',
                    selectedMissile: {
                        type: 'Missile',
                        subType: 'Missile',
                        size: 3,
                        grade: 'A',
                        name: 'Arrester III',
                        shortName: 'Arrstr III',
                        description:
                            'Using cross section targeting to hunt for its prey, the Firestorm Arrester proximity missile makes quick work of enemies caught in the crosshairs.',
                        physics: {
                            mass: 119,
                            temperature: {
                                enable: false,
                                initialTemperature: -1,
                                coolingEqualizationMultiplier: true,
                                internalTemperatureGeneration: false,
                                signatureParams: {
                                    enable: false,
                                    minimumTemperatureForIR: 250,
                                    temperatureToIR: 6,
                                },
                                itemResourceParams: {
                                    minOperatingTemperature: 0,
                                    minCoolingTemperature: 300,
                                    enableOverheat: false,
                                    overheatTemperature: 450,
                                    overheatWarningTemperature: 370,
                                    overheatRecoveryTemperature: 350,
                                },
                            },
                        },
                        health: {
                            hp: 50,
                            damageResistanceMultiplier: {
                                physical: 1,
                                energy: 1,
                                distortion: 1,
                                thermal: 1,
                                biochemical: 0,
                                stun: 0,
                            },
                        },
                        ref: 'dee6efca-71ef-438c-b762-624f9ce649f3',
                        distortion: {
                            decayDelay: 1.5,
                            decayRate: 40,
                            maximum: 1000,
                            warningRatio: 0.75,
                            recoveryRatio: 0.7,
                            powerRatioAtMaxDistortion: false,
                            powerChangeOnlyAtMaxDistortion: true,
                        },
                        missile: {
                            explosionSafetyDistance: 5,
                            projectileProximity: 1,
                            armTime: 1.5,
                            igniteTime: 0.3,
                            collisionDelayTime: 0.5,
                            irSignalMinValue: 0,
                            irSignalMaxValue: 0,
                            irSignalRiseRate: 0,
                            irSignalDecayRate: 0,
                            trackingSignalType: 'CrossSection',
                            lockSignalAmplifier: 2.5,
                            lockTime: 1,
                            lockingAngle: 60,
                            minRatioForLock: 1,
                            lockIncreaseRate: 1.3,
                            lockDecreaseRate: 9999,
                            lockRangeMin: 1900,
                            lockRangeMax: 25000,
                            lockResolutionRadius: 700,
                            signalResilienceMin: 1,
                            signalResilienceMax: 1.7,
                            linearSpeed: 857.5,
                            fuelTankSize: 50,
                            maxLifetime: 0,
                            minRadius: 0.25,
                            maxRadius: 3,
                            minPhysRadius: 20,
                            maxPhysRadius: 25,
                            hitType: 'explosion',
                            damage: {
                                damagePhysical: 2526.42,
                                damageEnergy: 0,
                                damageDistortion: 0,
                                damageThermal: 0,
                                damageBiochemical: 0,
                                damageStun: 0,
                            },
                        },
                        manufacturerData: {
                            calculatorType: 'manufacturer',
                            data: {
                                nameSmall: 'FSKI',
                                ref: '5f81335d-44e6-4104-841e-c5af9df06829',
                                name: 'FireStorm Kinetics',
                                calculatorName: 'FSKI',
                            },
                        },
                    },
                },
            ],
            pdcCount: 7,
        },
    },
]
